### ISSUE TITLE
incompatibility with pyhton 3.11.4

### ISSUE THREAD

**Issue by khal4n1** [cr0hn/festin#4]
when Im trying to run festin Im getting this error

└─$ festin -h

[!] Python 3.8 or above is required

If you don't want to install Python 3.8. Try with Docker:

   $ docker run --rm cr0hn/festin -h

any clue?

**Comment by khal4n1** [comment]
im using a vm with 6.3.0-kali1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1kali1 (2023-06-29) x86_64 GNU/Linux

**Comment by cr0hn** [comment]
You need to run Python 3.8 or higher. I don't know what version is included in Kali 6.3.0, sorry.
